-- Enable the pg_trgm extension if not exists to support GIN trigram indexes
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Create GIN indexes on full-text search columns
CREATE INDEX IF NOT EXISTS "movies_title_gin_idx" ON "movies" USING GIN ("title" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "movies_originalTitle_gin_idx" ON "movies" USING GIN ("originalTitle" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "movies_synopsis_gin_idx" ON "movies" USING GIN ("synopsis" gin_trgm_ops);

-- Add standard B-tree indexes generated by Prisma for foreign keys
CREATE INDEX IF NOT EXISTS "movies_deletedAt_idx" ON "movies"("deletedAt");
CREATE INDEX IF NOT EXISTS "movie_people_personId_idx" ON "movie_people"("personId");
CREATE INDEX IF NOT EXISTS "movie_genres_genreId_idx" ON "movie_genres"("genreId");
CREATE INDEX IF NOT EXISTS "movie_tags_tagId_idx" ON "movie_tags"("tagId");
CREATE INDEX IF NOT EXISTS "collection_movies_movieId_idx" ON "collection_movies"("movieId");
