allowBuilds:
  '@prisma/engines': set this to true or false
  '@sentry/cli': true
  prisma: set this to true or false
  sharp: true
  unrs-resolver: true
ignoreScripts: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
