tunnel: REPLACE_WITH_TUNNEL_UUID
credentials-file: /home/container/.cloudflared/REPLACE_WITH_TUNNEL_UUID.json

ingress:
  - hostname: www.movieflix.site
    service: http://movieflix.internal:3000
    originRequest:
      connectTimeout: 10s
      noHappyEyeballs: false
  - service: http_status:404
